# Final

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
!gdown --id 1dkIQbawpE7BKnxGh_OTKI1qVHWCuhCXh # mtp_data.csv
!gdown --id 1g6l_m0Qdxqg_LLed5W73EfB8ZZpwxAzR # run svr
!gdown --id 1e_OMi-qlD1LDrEPwJY7cXYH8uuIUzhB5 # run lstm
!gdown --id 1T8NpfQ_cSq5yXGBtrblLSquszd4dH_tg # run lr
!gdown --id 1OTlVP9h2cM6j89C3MSjzaYhehwPUphZq # lr asset selection
!gdown --id 1b1IxAxjZo29GeMbz1vbcaSuVnHCnB7LL # svr asset selection
!gdown --id 1-g7ypg87-io1Pp2Cci9Z2q8nGluA8oVp # lstm asset selection

In [ ]:
pd.read_csv('/content/mtp_data.csv', index_col=0).head()

^NSEI     ONGC.NS      UPL.NS      ITC.NS  SUNPHARMA.NS      IOC.NS  \
0  10283.599609  142.570755  461.820221  219.472366    497.929108  137.465652   
1  10298.750000  144.497406  464.817383  220.493179    497.977264  136.700287   
2  10326.900391  145.219864  481.142456  217.600906    518.102356  137.813507   
3  10342.299805  145.541016  476.423492  219.599976    515.406250  137.761353   
4  10348.750000  145.862076  477.762665  219.599976    524.553955  137.326477   

   JSWSTEEL.NS     SBIN.NS   SHREECEM.NS  HINDUNILVR.NS  ...  KOTAKBANK.NS  \
0   243.074020  334.412537  17980.212891    1207.996460  ...   1021.619751   
1   242.481430  329.953705  17216.855469    1204.546875  ...   1038.942871   
2   245.125443  327.625183  16725.525391    1207.240234  ...   1028.259399   
3   244.851959  332.232635  16819.513672    1200.719116  ...   1024.664917   
4   243.301971  331.885864  16929.433594    1197.930908  ...   1020.521423   

   BAJAJFINSV.NS  POWERGRID.NS  ASIANPAINT.NS  EICHERMOT.NS  TATAMOTORS.NS  \
0    5122.470215    124.082924    1140.235840   2765.153076     421.799988   
1    5166.208008    124.201874    1135.416992   2759.052246     423.000000   
2    5198.812012    122.893265    1129.527710   2739.318359     424.250000   
3    5169.003906    123.160934    1143.156372   2717.494873     428.600006   
4    5126.314941    124.350624    1128.845825   2757.274170     426.250000   

    DRREDDY.NS  HDFCBANK.NS      HDFC.NS    MARUTI.NS  
0  2228.211426   895.502197  1609.008423  7966.571289  
1  2182.017822   901.682983  1593.630493  8040.337402  
2  2296.853027   905.656372  1598.630859  8039.525879  
3  2264.714844   910.071228  1620.942749  8123.835449  
4  2212.525879   903.988525  1608.159302  8076.360840  

[5 rows x 51 columns]

In [ ]:
# %pycat run_lstm_train.sh

In [ ]:
# %%writefile run_lstm_train.sh

Overwriting run_lstm_train.sh


In [ ]:
!bash run_lr_train.sh

(954, 51)
(954, 51)
(954, 51)
(954, 51)
(954, 51)


In [ ]:
!bash run_svr_train.sh

(954, 51)
(954, 51)
(954, 51)
(954, 51)
(954, 51)


In [ ]:
!bash run_lstm_train.sh

Model Updated
Epoch: 0, train loss: 0.26649, val loss: 0.11721
Model Updated
Epoch: 100, train loss: 0.00490, val loss: 0.01681
Model Updated
Epoch: 200, train loss: 0.00234, val loss: 0.01453
Model Updated
Epoch: 300, train loss: 0.00165, val loss: 0.01187
Model Updated
Epoch: 400, train loss: 0.00131, val loss: 0.01082
Model Updated
Epoch: 500, train loss: 0.00121, val loss: 0.01040
Model Updated
Epoch: 600, train loss: 0.00095, val loss: 0.00924
Model Updated
Epoch: 700, train loss: 0.00090, val loss: 0.00850
Model Updated
Epoch: 800, train loss: 0.00091, val loss: 0.00757
Model Updated
Epoch: 900, train loss: 0.00074, val loss: 0.00713
Model Updated
Epoch: 1000, train loss: 0.00065, val loss: 0.00701
Model Updated
Epoch: 1100, train loss: 0.00060, val loss: 0.00666
Model Updated
Epoch: 1200, train loss: 0.00058, val loss: 0.00663
Epoch: 1300, train loss: 0.00057, val loss: 0.00663
Model Updated
Epoch: 1400, train loss: 0.00051, val loss: 0.00632
Model Updated
Epoch: 1500, train los

In [ ]:
np.sort(np.load('/content/LR_StockPicking/10/top_idxs.npy'))

array([ 1, 13, 15, 21, 23, 29, 30, 39, 42, 44])

In [ ]:
np.sort(np.load('/content/SVR_StockPicking/10/top_idxs.npy'))

array([ 1,  3,  5, 10, 21, 23, 24, 34, 40, 50])

In [ ]:
# !zip -r /content/LR_StockPicking.zip /content/LR_StockPicking
# !zip -r /content/SVR_StockPicking.zip /content/SVR_StockPicking
!zip -r /content/LSTM_StockPicking_window_5.zip /content/LSTM_StockPicking_window_5

# TEMP

In [ ]:
!gdown --id 1dkIQbawpE7BKnxGh_OTKI1qVHWCuhCXh
!gdown --id 
!gdown --id 

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1dkIQbawpE7BKnxGh_OTKI1qVHWCuhCXh
To: /content/mtp_data.csv
100% 851k/851k [00:00<00:00, 22.5MB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1aR_9DxDYROg0gy3vlajzrcGCNoXher6E
To: /content/run_lr_train.sh
100% 682/682 [00:00<00:00, 1.15MB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: http

In [ ]:
!bash run_lr_train.sh

(954, 51)
(954, 51)
(954, 51)
(954, 51)
(954, 51)


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.sort(np.load('/content/LR_Data2/1/top_idxs.npy'))

array([ 1,  3,  5, 10, 17, 19, 21, 23, 28, 31, 38, 40, 41, 48, 50])

In [ ]:
np.sort(np.load('/content/LR_Data2/5/top_idxs.npy'))

array([ 1,  3, 10, 11, 13, 21, 23, 24, 28, 29, 30, 39, 41, 42, 45])

In [ ]:
pd.read_csv('/content/mtp_data.csv', index_col=0)

^NSEI     ONGC.NS      UPL.NS      ITC.NS  SUNPHARMA.NS  \
0    10283.599609  142.570755  461.820221  219.472366    497.929108   
1    10298.750000  144.497406  464.817383  220.493179    497.977264   
2    10326.900391  145.219864  481.142456  217.600906    518.102356   
3    10342.299805  145.541016  476.423492  219.599976    515.406250   
4    10348.750000  145.862076  477.762665  219.599976    524.553955   
..            ...         ...         ...         ...           ...   
949  17822.949219  131.455353  726.849976  237.023010    763.822693   
950  17853.199219  129.880753  718.650024  233.064484    764.418030   
951  17855.099609  133.602539  725.849976  233.308838    757.075989   
952  17748.599609  135.701996  716.799988  232.380295    769.031616   
953  17711.300781  138.135483  717.150024  232.722397    804.948242   

         IOC.NS  JSWSTEEL.NS     SBIN.NS   SHREECEM.NS  HINDUNILVR.NS  ...  \
0    137.465652   243.074020  334.412537  17980.212891    1207.996460  ...   
1    136.700287   242.481430  329.953705  17216.855469    1204.546875  ...   
2    137.813507   245.125443  327.625183  16725.525391    1207.240234  ...   
3    137.761353   244.851959  332.232635  16819.513672    1200.719116  ...   
4    137.326477   243.301971  331.885864  16929.433594    1197.930908  ...   
..          ...          ...         ...           ...            ...  ...   
949  110.018982   677.250000  449.799988  29866.380859    2765.306152  ...   
950  109.319702   659.150024  440.750000  29359.828125    2729.873779  ...   
951  110.625015   648.650024  446.600006  29423.914062    2692.950684  ...   
952  114.634171   660.849976  444.899994  29191.275391    2707.213135  ...   
953  118.829811   679.799988  460.000000  29330.480469    2668.898682  ...   

     KOTAKBANK.NS  BAJAJFINSV.NS  POWERGRID.NS  ASIANPAINT.NS  EICHERMOT.NS  \
0     1021.619751    5122.470215    124.082924    1140.235840   2765.153076   
1     1038.942871    5166.208008    124.201874    1135.416992   2759.052246   
2     1028.259399    5198.812012    122.893265    1129.527710   2739.318359   
3     1024.664917    5169.003906    123.160934    1143.156372   2717.494873   
4     1020.521423    5126.314941    124.350624    1128.845825   2757.274170   
..            ...            ...           ...            ...           ...   
949   2024.000000   18503.849609    170.912872    3316.733398   2857.050049   
950   2028.099976   18526.000000    168.899323    3444.532715   2931.000000   
951   2033.349976   18031.099609    168.755493    3426.603516   2879.350098   
952   2068.199951   17550.349609    176.378265    3375.713623   2883.050049   
953   2030.449951   17433.750000    187.021362    3319.130615   2843.250000   

     TATAMOTORS.NS   DRREDDY.NS  HDFCBANK.NS      HDFC.NS    MARUTI.NS  
0       421.799988  2228.211426   895.502197  1609.008423  7966.571289  
1       423.000000  2182.017822   901.682983  1593.630493  8040.337402  
2       424.250000  2296.853027   905.656372  1598.630859  8039.525879  
3       428.600006  2264.714844   910.071228  1620.942749  8123.835449  
4       426.250000  2212.525879   903.988525  1608.159302  8076.360840  
..             ...          ...          ...          ...          ...  
949     321.500000  4797.299805  1570.000000  2817.399902  6846.700195  
950     317.950012  4790.350098  1601.550049  2839.000000  6952.250000  
951     331.649994  4791.649902  1625.099976  2839.800049  7403.450195  
952     329.299988  4833.149902  1615.050049  2804.949951  7423.850098  
953     330.250000  4881.000000  1593.849976  2746.449951  7384.049805  

[954 rows x 51 columns]

In [ ]:
%pycat run_lr_train.sh

In [ ]:
%%writefile run_lr_train.sh
python lr_asset_selection.py --exp_name LR_StockPicking/2 --test_size 0.02 --num_stocks 10
python lr_asset_selection.py --exp_name LR_StockPicking/4 --test_size 0.04 --num_stocks 10
python lr_asset_selection.py --exp_name LR_StockPicking/6 --test_size 0.06 --num_stocks 10
python lr_asset_selection.py --exp_name LR_StockPicking/8 --test_size 0.08 --num_stocks 10
python lr_asset_selection.py --exp_name LR_StockPicking/10 --test_size 0.1 --num_stocks 10

Overwriting run_lr_train.sh


In [ ]:
%pycat lr_asset_selection.py

In [ ]:
%%writefile lr_asset_selection.py
import os
import json
import argparse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Function to prepare data
def prepare_data(X, window_size, sc = None):
    '''
    window_size : number of timesteps to look back for predicting the next timestep
    '''
    nAssets = X.shape[1]
    if sc is None:
        sc = MinMaxScaler()
        X = sc.fit_transform(X)
    else:
        X = sc.transform(X)
    
    x = []
    y = []
    dim=X.shape[1]
    for i in range(window_size, X.shape[0]):
        x.append(X[(i - window_size):i, :].reshape(window_size, dim))
        y.append(X[i, :].reshape(1, dim))
    
    x = np.array(x); y = np.squeeze(np.array(y));
    
    return x.reshape(-1, nAssets * window_size), y, sc

def make_grid_plot(y,preds):

    # Hard coded for 51 assets (i.e. plots); needs change in values if the number of input assets are changed
    fig, axs = plt.subplots(17, 3, figsize = (15,30))

    for i in range(17):
        for j in range(3):
            idx = i*3 + j
            axs[i,j].plot(preds[:, idx], color = 'orange', label = 'preds')
            axs[i,j].plot(sc.inverse_transform(y)[:, idx], color = 'blue', label = 'true')
            axs[i,j].legend(loc = 'upper left')
    return fig


# Parse Arguments
parser = argparse.ArgumentParser()
parser.add_argument("-ename", "--exp_name", type = str, default = "default_exp",
                    help = "Path to output folder for trained model")
parser.add_argument("-tsize", "--test_size", type = float, default = 0.1,
                    help = "Test Size")
parser.add_argument("-ws", "--window_size", type = int, default = 5,
                    help = "Window Size")
parser.add_argument("-nstocks", "--num_stocks", type = int, default = 4,
                    help = "Number of stocks to be picked for portfolio")
args = parser.parse_args()


EXP_NAME = args.exp_name
# Make experiment directory #
if not os.path.exists(args.exp_name):
        os.makedirs(args.exp_name)

# Reading data
data = pd.read_csv('mtp_data.csv', index_col = 0)
data = np.array(data.iloc[:, :])

# Split into training, validation and testing parts
X_train, X_test = train_test_split(data, test_size = args.test_size, shuffle = False)
_xtrain = np.copy(X_train)
X_test = np.vstack([X_train[X_train.shape[0] - args.window_size:X_train.shape[0], :], X_test])

xtr, ytr, sc = prepare_data(X_train, args.window_size)
xte, yte, _ = prepare_data(X_test, args.window_size, sc)
reg = LinearRegression().fit(xtr, ytr)
preds = sc.inverse_transform(reg.predict(xte))

# Pick top 'num_stocks' best stocks #
num_stocks = X_train.shape[1]
X = preds
R = np.copy(X)
for i in range(1, R.shape[0]):
    R[i] = (X[i] - X[i-1])/X[i-1]
    
R = R[1:, :]

expected_returns = {}
for i in range(num_stocks):
    expected_returns[i] = np.mean(R[:, i])

top_idxs = list(dict(sorted(expected_returns.items(), key = lambda item: item[1], reverse = True)).keys())[:args.num_stocks]
np.save(os.path.join(EXP_NAME, 'top_idxs.npy'), np.array(top_idxs))

with open(os.path.join(EXP_NAME, 'commandline_args.txt'), 'w') as f:
    json.dump(args.__dict__, f, indent = 2)


# Save predictions on test set along with other data #
arr = np.vstack([_xtrain, preds])
print(arr.shape)
np.save(os.path.join(EXP_NAME, 'preds_array.npy'), arr)

preds_tr = sc.inverse_transform(reg.predict(xtr))
train_fig = make_grid_plot(ytr,preds_tr)
test_fig = make_grid_plot(yte,preds)
train_fig.savefig(os.path.join(EXP_NAME, 'train_plot.png'))
test_fig.savefig(os.path.join(EXP_NAME, 'test_plot.png'))

Overwriting lr_asset_selection.py


In [ ]:
%pycat run_lr_train.sh